version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www/html/frontend
      - ./backend:/var/www/html/backend
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    command: /bin/bash -c "service mysql start && apache2-foreground"
